# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import grpcbin_pb2 as grpcbin__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in grpcbin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GRPCBinStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Index = channel.unary_unary(
                '/grpcbin.GRPCBin/Index',
                request_serializer=grpcbin__pb2.EmptyMessage.SerializeToString,
                response_deserializer=grpcbin__pb2.IndexReply.FromString,
                _registered_method=True)
        self.Empty = channel.unary_unary(
                '/grpcbin.GRPCBin/Empty',
                request_serializer=grpcbin__pb2.EmptyMessage.SerializeToString,
                response_deserializer=grpcbin__pb2.EmptyMessage.FromString,
                _registered_method=True)
        self.DummyUnary = channel.unary_unary(
                '/grpcbin.GRPCBin/DummyUnary',
                request_serializer=grpcbin__pb2.DummyMessage.SerializeToString,
                response_deserializer=grpcbin__pb2.DummyMessage.FromString,
                _registered_method=True)
        self.DummyServerStream = channel.unary_stream(
                '/grpcbin.GRPCBin/DummyServerStream',
                request_serializer=grpcbin__pb2.DummyMessage.SerializeToString,
                response_deserializer=grpcbin__pb2.DummyMessage.FromString,
                _registered_method=True)
        self.DummyClientStream = channel.stream_unary(
                '/grpcbin.GRPCBin/DummyClientStream',
                request_serializer=grpcbin__pb2.DummyMessage.SerializeToString,
                response_deserializer=grpcbin__pb2.DummyMessage.FromString,
                _registered_method=True)
        self.DummyBidirectionalStreamStream = channel.stream_stream(
                '/grpcbin.GRPCBin/DummyBidirectionalStreamStream',
                request_serializer=grpcbin__pb2.DummyMessage.SerializeToString,
                response_deserializer=grpcbin__pb2.DummyMessage.FromString,
                _registered_method=True)
        self.SpecificError = channel.unary_unary(
                '/grpcbin.GRPCBin/SpecificError',
                request_serializer=grpcbin__pb2.SpecificErrorRequest.SerializeToString,
                response_deserializer=grpcbin__pb2.EmptyMessage.FromString,
                _registered_method=True)
        self.RandomError = channel.unary_unary(
                '/grpcbin.GRPCBin/RandomError',
                request_serializer=grpcbin__pb2.EmptyMessage.SerializeToString,
                response_deserializer=grpcbin__pb2.EmptyMessage.FromString,
                _registered_method=True)
        self.HeadersUnary = channel.unary_unary(
                '/grpcbin.GRPCBin/HeadersUnary',
                request_serializer=grpcbin__pb2.EmptyMessage.SerializeToString,
                response_deserializer=grpcbin__pb2.HeadersMessage.FromString,
                _registered_method=True)
        self.NoResponseUnary = channel.unary_unary(
                '/grpcbin.GRPCBin/NoResponseUnary',
                request_serializer=grpcbin__pb2.EmptyMessage.SerializeToString,
                response_deserializer=grpcbin__pb2.EmptyMessage.FromString,
                _registered_method=True)


class GRPCBinServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Index(self, request, context):
        """This endpoint
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Empty(self, request, context):
        """Unary endpoint that takes no argument and replies an empty message.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DummyUnary(self, request, context):
        """Unary endpoint that replies a received DummyMessage
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DummyServerStream(self, request, context):
        """Stream endpoint that sends back 10 times the received DummyMessage
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DummyClientStream(self, request_iterator, context):
        """Stream endpoint that receives 10 DummyMessages and replies with the last received one
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DummyBidirectionalStreamStream(self, request_iterator, context):
        """Stream endpoint that sends back a received DummyMessage indefinitely (chat mode)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SpecificError(self, request, context):
        """Unary endpoint that raises a specified (by code) gRPC error
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RandomError(self, request, context):
        """Unary endpoint that raises a random gRPC error
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HeadersUnary(self, request, context):
        """Unary endpoint that returns headers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NoResponseUnary(self, request, context):
        """Unary endpoint that returns no respnose
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GRPCBinServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Index': grpc.unary_unary_rpc_method_handler(
                    servicer.Index,
                    request_deserializer=grpcbin__pb2.EmptyMessage.FromString,
                    response_serializer=grpcbin__pb2.IndexReply.SerializeToString,
            ),
            'Empty': grpc.unary_unary_rpc_method_handler(
                    servicer.Empty,
                    request_deserializer=grpcbin__pb2.EmptyMessage.FromString,
                    response_serializer=grpcbin__pb2.EmptyMessage.SerializeToString,
            ),
            'DummyUnary': grpc.unary_unary_rpc_method_handler(
                    servicer.DummyUnary,
                    request_deserializer=grpcbin__pb2.DummyMessage.FromString,
                    response_serializer=grpcbin__pb2.DummyMessage.SerializeToString,
            ),
            'DummyServerStream': grpc.unary_stream_rpc_method_handler(
                    servicer.DummyServerStream,
                    request_deserializer=grpcbin__pb2.DummyMessage.FromString,
                    response_serializer=grpcbin__pb2.DummyMessage.SerializeToString,
            ),
            'DummyClientStream': grpc.stream_unary_rpc_method_handler(
                    servicer.DummyClientStream,
                    request_deserializer=grpcbin__pb2.DummyMessage.FromString,
                    response_serializer=grpcbin__pb2.DummyMessage.SerializeToString,
            ),
            'DummyBidirectionalStreamStream': grpc.stream_stream_rpc_method_handler(
                    servicer.DummyBidirectionalStreamStream,
                    request_deserializer=grpcbin__pb2.DummyMessage.FromString,
                    response_serializer=grpcbin__pb2.DummyMessage.SerializeToString,
            ),
            'SpecificError': grpc.unary_unary_rpc_method_handler(
                    servicer.SpecificError,
                    request_deserializer=grpcbin__pb2.SpecificErrorRequest.FromString,
                    response_serializer=grpcbin__pb2.EmptyMessage.SerializeToString,
            ),
            'RandomError': grpc.unary_unary_rpc_method_handler(
                    servicer.RandomError,
                    request_deserializer=grpcbin__pb2.EmptyMessage.FromString,
                    response_serializer=grpcbin__pb2.EmptyMessage.SerializeToString,
            ),
            'HeadersUnary': grpc.unary_unary_rpc_method_handler(
                    servicer.HeadersUnary,
                    request_deserializer=grpcbin__pb2.EmptyMessage.FromString,
                    response_serializer=grpcbin__pb2.HeadersMessage.SerializeToString,
            ),
            'NoResponseUnary': grpc.unary_unary_rpc_method_handler(
                    servicer.NoResponseUnary,
                    request_deserializer=grpcbin__pb2.EmptyMessage.FromString,
                    response_serializer=grpcbin__pb2.EmptyMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpcbin.GRPCBin', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grpcbin.GRPCBin', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GRPCBin(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Index(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpcbin.GRPCBin/Index',
            grpcbin__pb2.EmptyMessage.SerializeToString,
            grpcbin__pb2.IndexReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Empty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpcbin.GRPCBin/Empty',
            grpcbin__pb2.EmptyMessage.SerializeToString,
            grpcbin__pb2.EmptyMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DummyUnary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpcbin.GRPCBin/DummyUnary',
            grpcbin__pb2.DummyMessage.SerializeToString,
            grpcbin__pb2.DummyMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DummyServerStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/grpcbin.GRPCBin/DummyServerStream',
            grpcbin__pb2.DummyMessage.SerializeToString,
            grpcbin__pb2.DummyMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DummyClientStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/grpcbin.GRPCBin/DummyClientStream',
            grpcbin__pb2.DummyMessage.SerializeToString,
            grpcbin__pb2.DummyMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DummyBidirectionalStreamStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/grpcbin.GRPCBin/DummyBidirectionalStreamStream',
            grpcbin__pb2.DummyMessage.SerializeToString,
            grpcbin__pb2.DummyMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SpecificError(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpcbin.GRPCBin/SpecificError',
            grpcbin__pb2.SpecificErrorRequest.SerializeToString,
            grpcbin__pb2.EmptyMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RandomError(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpcbin.GRPCBin/RandomError',
            grpcbin__pb2.EmptyMessage.SerializeToString,
            grpcbin__pb2.EmptyMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HeadersUnary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpcbin.GRPCBin/HeadersUnary',
            grpcbin__pb2.EmptyMessage.SerializeToString,
            grpcbin__pb2.HeadersMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NoResponseUnary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpcbin.GRPCBin/NoResponseUnary',
            grpcbin__pb2.EmptyMessage.SerializeToString,
            grpcbin__pb2.EmptyMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
