/**
 * Manual API layer for the unified events API.
 *
 * Types are imported from `./schema` (generated by openapi-typescript from the
 * server's OpenAPI spec). This module re-exports them under friendly names and
 * wraps each endpoint in a fetch + React Query hook.
 */
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import type { UseQueryOptions, UseMutationOptions } from "@tanstack/react-query";

import type { components } from "./schema";

// --- Types (re-exported from generated schema) ---

export type EventSummary = components["schemas"]["EventSummary"];
export type EventDetail = components["schemas"]["EventDetail"];
export type HttpEventData = components["schemas"]["HttpEventData"];
export type LogEventData = components["schemas"]["LogEventData"];
export type ExceptionEventData = components["schemas"]["ExceptionEventData"];
export type ExceptionFrame = components["schemas"]["ExceptionFrame"];
export type MetaResponse = components["schemas"]["MetaResponse"];
export type EventType = EventSummary["event_type"];

export interface ListEventsParams {
  event_type?: string;
  host?: string;
  method?: string;
  status?: number;
  search?: string;
  limit?: number;
}

// --- Fetch functions ---

async function fetchJson<T>(url: string, init?: RequestInit): Promise<T> {
  const res = await fetch(url, init);
  if (!res.ok) throw new Error(`${res.status} ${res.statusText}`);
  if ([204, 205, 304].includes(res.status)) return {} as T;
  return res.json();
}

function buildUrl(path: string, params?: Record<string, string | number | undefined>): string {
  const url = new URL(path, window.location.origin);
  if (params) {
    for (const [k, v] of Object.entries(params)) {
      if (v !== undefined && v !== "") url.searchParams.set(k, String(v));
    }
  }
  return url.toString();
}

export async function listEvents(params?: ListEventsParams): Promise<EventSummary[]> {
  return fetchJson(buildUrl("/api/events", params as Record<string, string | number | undefined>));
}

export async function getEvent(id: string): Promise<EventDetail> {
  return fetchJson(`/api/events/${id}`);
}

export async function getMeta(): Promise<MetaResponse> {
  return fetchJson("/api/meta");
}

export async function clearEvents(): Promise<void> {
  await fetch("/api/events", { method: "DELETE" });
}

// --- Query keys ---

export const eventKeys = {
  all: ["/api/events"] as const,
  list: (params?: ListEventsParams) => ["/api/events", params] as const,
  detail: (id: string) => ["/api/events", id] as const,
  meta: ["/api/meta"] as const,
};

// --- React Query hooks ---

export function useListEvents(
  params?: ListEventsParams,
  options?: Partial<UseQueryOptions<EventSummary[]>>,
) {
  return useQuery({
    queryKey: eventKeys.list(params),
    queryFn: () => listEvents(params),
    ...options,
  });
}

export function useGetEvent(id: string, options?: Partial<UseQueryOptions<EventDetail>>) {
  return useQuery({
    queryKey: eventKeys.detail(id),
    queryFn: () => getEvent(id),
    enabled: !!id,
    ...options,
  });
}

export function useGetMeta(options?: Partial<UseQueryOptions<MetaResponse>>) {
  return useQuery({
    queryKey: eventKeys.meta,
    queryFn: getMeta,
    ...options,
  });
}

export function useClearEvents(options?: UseMutationOptions<void, Error, void>) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: clearEvents,
    onSuccess: (...args) => {
      queryClient.invalidateQueries({ queryKey: eventKeys.all });
      queryClient.invalidateQueries({ queryKey: eventKeys.meta });
      options?.onSuccess?.(...args);
    },
    ...options,
  });
}
